#logging:
#  level:
#    root: debug
server:
  port: 9000
spring:
  application:
    name: spring-gateway-demo
  cloud:
    gateway:
      routes:
        - id: route2
          uri: http://httpbin.org
          predicates:
            - Path=/post
